### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Eisblume-2000** [Turpo2098/MCMusicBooks#1]
please add the ability to group players so that you can play complex songs
currently, it would be almost impossible to synchronize multiple people for complex song-playing

please change the wait delay variable from milliseconds to bpm
the correct conversion formal should be 60/bpm*100

**Comment by ClientAPII** [comment]
- you can just use `def w wait 500` and then just use `w` for every pause.

- You can already play complex songs just write everything in one book
